### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by jonniebigodes** [bitovi/github-actions-storybook-to-github-pages#3]
While testing this action as part of the following [pull request](https://github.com/storybookjs/storybook/pull/24527), I've encountered an issue with the action throwing an error if a different package manager (i.e., Yarn) was provided, leaving me and other users in a state where they're unable to publish their Storybook documentation unless they use npm.

For context, I've set up a small reproduction [here](https://github.com/jonniebigodes/test-deployer-gh-actions) and looking at the action [runs](https://github.com/jonniebigodes/test-deployer-gh-actions/actions) I was wondering if there's an opening for supporting Yarn as a package manager so that the associated Storybook documentation pull request can be reviewed properly and get merged in and make it available to our readers.

Let me know and we'll go from there.

Hope you have a fantastic rest of the week.

Stay safe

**Comment by mickmcgrath13** [comment]
Hey @jonniebigodes,

The [default build command](https://github.com/bitovi/github-actions-storybook-to-github-pages/blob/main/action.yaml#L20) is `npm run build-storybook`.

The `build_command` input allows this to be overwritten to:
```
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
      with:
        build_command: yarn run build-storybook
```

However, we should surface the install command as well (similar [to this](https://github.com/bitovi/github-actions-react-to-github-pages/blob/main/action.yaml#L15-L18)):
```
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
      with:
        install_command: yarn install
        build_command: yarn run build-storybook
```
