### ISSUE TITLE
No uploaded artifact was found!

### ISSUE THREAD

**Issue by adriansmierciaktsh** [bitovi/github-actions-storybook-to-github-pages#6]
Artifact exchange URL: https://pipelinesghubeus9.actions.githubusercontent.com/U75tv9vGjEbD6ncDaJJHwN3tmcm6NWn3Y6dcQr2iyjh0T4I1lG/_apis/pipelines/workflows/7221683194/artifacts?api-version=6.0-preview

Error: Error: No uploaded artifact was found! Please check if there are any errors at build step, or uploaded artifact name is correct.
    at getSignedArtifactUrl (/home/runner/work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/src/api-client.js:93:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/src/deployment.js:53:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/src/index.js:30:1)

**Comment by pkmelee337** [comment]
Yup, I encountered the same issue. Looks like a change in deploy-pages github action

**Comment by LeoDiazL** [comment]
Hi @adriansmierciaktsh @pkmelee337, thanks for opening up an issue!

Do you have the following block in your workflow?
```
permissions:
  contents: read
  pages: write
  id-token: write
```

You should end with a workflow similar to this:
```
name: Build and Publish storybook to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
      with:
        path: storybook-static # change to your build folder
        install_command: npm ci
        build_command: npm run build-storybook
```

Just in case, have you configured [this](https://github.com/marketplace/actions/deploy-storybook-to-github-pages#set-up-your-project-for-actions-deployed-pages) too?

Let me know if you do, and I'll dig deeper.

**Comment by blaise2s** [comment]
I subscribed to this thread for updates when there was a fix... to keep things moving along, yes, I already had the below block in my workflow file and "GitHub Actions" selected as the source for "Build and deployment" and saw this issue happening this morning.

```yml
permissions:
  contents: read
  pages: write
  id-token: write
```

<img width="276" alt="Screenshot 2023-12-15 at 6 39 30 PM" src="https://github.com/bitovi/github-actions-storybook-to-github-pages/assets/13556827/ded3c2c1-6459-4266-ae3d-4258c47eeadc">
