### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by thenick775** [bitovi/github-actions-storybook-to-github-pages#9]
Some simple updates would fix this warning when using this awesome plugin:

<img width="884" alt="Screenshot 2024-02-25 at 7 38 12 PM" src="https://github.com/bitovi/github-actions-storybook-to-github-pages/assets/40526638/49f4b831-ee4f-428e-b870-df672aa37f02">

Example:

- Run any pipeline using the latest version of this GitHub action:
```
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        name: Storybook Deploy
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          path: storybook-static
          # want a separate workflow, required prod build to generate type definition
          build_command: npm run build && npm run build-storybook
```

I'll attempt to make a pr as I'm available if a maintainer can't get to it first!
